ADD_NEW_BUTTON_LOCATOR  = "xpath=//button[contains(@class, 'add-address-button')]"
FIRST_NAME_ADDRESS_LOCATOR  =   "id:Address_FirstName"
LAST_NAME_ADDRESS_LOCATOR   =   "id:Address_LastName"
EMAIL_NAME_ADDRESS_LOCATOR  =   "id:Address_Email"
COMPANY_NAME_ADDRESS_LOCATOR    =   "id:Address_Company"
COUNTRY_DROPDOWN_LOCATOR    =   "id:Address_CountryId"
PROVINCE_DROPDOWN_LOCATOR   = "id:Address_StateProvinceId"
CITY_TEXTBOX_LOCATOR    = "id:Address_City"
ADDRESS_1_TEXTBOX_LOCATOR    = "id:Address_Address1"
ADDRESS_2_TEXTBOX_LOCATOR    = "id:Address_Address2"
ZIP_TEXTBOX_LOCATOR    = "id:Address_ZipPostalCode"
PHONE_NUMBER_TEXTBOX_LOCATOR    = "id:Address_PhoneNumber"
FAX_NUMBER_TEXTBOX_LOCATOR    = "id:Address_FaxNumber"
SAVE_BUTTON_ADDRESS = "class:save-address-button"