REGISTER_LINK = "class:ico-register"
LOGIN_LINK = "class:ico-login"
MY_ACCOUNT_LINK = "class:ico-account"
LOG_OUT_LINK = "class:ico-logout"
NEW_PRODUCTS_LINK = "xpath=//div[@class='header-menu']//a[normalize-space(text())='Điện thoại']"
SEARCH_LINK = "xpath=//div[@class='header-menu']//a[normalize-space(text())='Search']"