REVIEW_TITLE_TEXTBOX_LOCATOR = "xpath=//input[@class='review-title']"
REVIEW_TEXT_TEXTBOX_LOCATOR = "xpath=//textarea[@class='review-text']"
RATING_RADIO_CHECKBOX_LOCATOR = "id:addproductrating_4"
SUBMIT_REVIEW_BUTTON_LOCATOR = "id:add-review"
CLOSE_BUTTON = "class:close"
ADD_TO_WISHLIST_BUTTON = "id:add-to-wishlist-button-3"
ADD_TO_COMPARE_BUTTON = "xpath=//div[@class='compare-products']/button"
ADD_TO_COMPARE_LINK = "css=.content>a"