REGISTER_BUTTON = "name:register-button"
FIRST_NAME_ERROR_MESSAGE = "xpath=//span[@id='FirstName-error']"
LAST_NAME_ERROR_MESSAGE = "xpath=//span[@id='LastName-error']"
EMAIL_ERROR_MESSAGE = "xpath=//span[@id='Email-error']"
PASSWORD_ERROR_MESSAGE = "xpath=//span[@id='ConfirmPassword-error']"

FIRST_NAME_TEXTBOX = "xpath=//input[@id='FirstName']"
LAST_NAME_TEXTBOX = "xpath=//input[@id='LastName']"
EMAIL_TEXTBOX = "xpath=//input[@id='Email']"
PASSWORD_TEXTBOX = "xpath=//input[@id='Password']"
CONFIRM_PASSWORD_TEXTBOX = "xpath=//input[@id='ConfirmPassword']"

FIRST_NAME_REQUIRED_TEXT = "First name is required."
LAST_NAME_REQUIRED_TEXT = "Last name is required."
EMAIL_REQUIRED_TEXT = "Email is required."
PASSWORD_REQUIRED_TEXT = "Password is required."
EMAIL_INVALID_TEXT = "Wrong email"