REGISTER_BUTTON_LOCATOR = "name:register-button"
FIRST_NAME_ERROR_MESSAGE_LOCATOR = "xpath=//span[@id='FirstName-error']"
LAST_NAME_ERROR_MESSAGE_LOCATOR = "xpath=//span[@id='LastName-error']"
EMAIL_ERROR_MESSAGE_LOCATOR = "xpath=//span[@id='Email-error']"
PASSWORD_ERROR_MESSAGE_LOCATOR = "xpath=//span[@id='ConfirmPassword-error']"
PASSWORD_INVALID_MESSAGE_LOCATOR = "xpath=//span[@class='field-validation-error']"

FIRST_NAME_TEXTBOX_LOCATOR = "xpath=//input[@id='FirstName']"
LAST_NAME_TEXTBOX_LOCATOR = "xpath=//input[@id='LastName']"
EMAIL_TEXTBOX_LOCATOR = "xpath=//input[@id='Email']"
PASSWORD_TEXTBOX_LOCATOR = "xpath=//input[@id='Password']"
CONFIRM_PASSWORD_TEXTBOX_LOCATOR = "xpath=//input[@id='ConfirmPassword']"

SUCCESS_REGISTER_TEXT_LOCATOR = "class:result"
EXISTING_EMAIL_MESSAGE_LOCATOR = "css:div.message-error li"