REGISTER_BUTTON = "name:register-button"
# FIRST_NAME_ERROR_MESSAGE = "id:FirstName-error"
# LAST_NAME_ERROR_MESSAGE = "id:LastName-error"
# EMAIL_ERROR_MESSAGE = "id:Email-error"
# PASSWORD_ERROR_MESSAGE = "id:ConfirmPassword-error"
FIRST_NAME_ERROR_MESSAGE = "xpath=//span[@id='FirstName-error']"
LAST_NAME_ERROR_MESSAGE = "xpath=//span[@id='LastName-error']"
EMAIL_ERROR_MESSAGE = "xpath=//span[@id='Email-error']"
PASSWORD_ERROR_MESSAGE = "xpath=//span[@id='ConfirmPassword-error']"

FIRST_NAME_REQUIRED_TEXT = "First name is required."
LAST_NAME_REQUIRED_TEXT = "Last name is required."
EMAIL_REQUIRED_TEXT = "Email is required."
PASSWORD_REQUIRED_TEXT = "Password is required."